# x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin

name: On tag
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          mkdir dist
          targets=( "x86_64-unknown-linux-gnu" "x86_64-pc-windows-msvc" "x86_64-apple-darwin" "aarch64-apple-darwin" )
          for target in "$targets"; do
            deno compile --target $target -o dist/$target main.ts
          done
      - run: ls -la dist
